name: Update Website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update index.html
        run: |
          echo "<p>Updated by ${{ github.actor }} on $(date)</p>" >> index.html

      - name: Update README
        run: |
           echo "### Updated by ${{ github.actor }} on $(date '+%Y-%m-%d %H:%M:%S') [Commit: $(git rev-parse --short HEAD)]" >> README.md
      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .

          git commit -m "Workflow update" || exit 0

          git push
